<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="scale_factor" value="0.007" />
    <link name="baymax_link">
        <visual>
        <geometry>
            <mesh filename="file:///home/nabil/ros2_ws/src/medibot/urdf/Baymax.STL" scale="${scale_factor} ${scale_factor} ${scale_factor}" />
        </geometry>
        <material name="white">
            <color rgba="1 1 1 1" />
        </material>
        <origin xyz="-0.1 0 ${base_height+wheel_radius+camera_height/2}" rpy="0 0 1.57" />
        </visual>
        <collision>
        <geometry>
            <mesh filename="file:///home/nabil/ros2_ws/src/medibot/urdf/Baymax.STL" scale="${scale_factor} ${scale_factor} ${scale_factor}" />
        </geometry>
        <origin xyz="-0.1 0 ${base_height+wheel_radius+camera_height/2}" rpy="0 0 1.57" />
        </collision>
        <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>
</robot>
